### ISSUE TITLE
what does "studyDesign" looks like?

### ISSUE THREAD

**Issue by dailypartita** [aminorberg/trap17-pkg#1]
Hellow, Dr. Anna Norberg
Can you please tell me in the case of your paper [Intraspecific host variation plays a key role in virus community assembly](https://www.nature.com/articles/s41467-020-19273-z), what does "studyDesign" means?
and could you please give me a demo of "studyDesign"?
this is error imformation, very thanks!
```R
> # 2.3 model fitting and cross-validation
> evals <- model_and_cv(dat = dat,
+                       dirs = dirs,
+                       variants = 1:3,
+                       sampling = sampling,
+                       start_iter = sampling$pred_start_iter,
+                       do_cv = TRUE,
+                       saveCVs = TRUE)
Error in Hmsc:::HmscRandomLevel(units = studyDesign[, i]) : 
  object 'studyDesign' not found
In addition: Warning message:
In model.matrix.default(~x - 1, model.frame(~x - 1), contrasts = FALSE) :
  non-list contrasts argument ignored
```

**Comment by aminorberg** [comment]
Hi

As the name implies, studyDesign refers to the hierarchical design or structure of the study data. For more information and examples on this, see this excellent book on Hmsc modelling: https://www.cambridge.org/core/books/joint-species-distribution-modelling/0D9FA93EA1DD408332A17266449668B3

Also, have a look at the GitHub repo of the method: https://github.com/hmsc-r/HMSC

Best,

Anna
